services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: medods_admin
      POSTGRES_PASSWORD: medods_password
      POSTGRES_DB: medods
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  go:
    build:
      context: .
      target: final
    container_name: go-app
    restart: always
    depends_on:
      postgres:
          condition: service_healthy
    ports:
      - "8082:8082"
    #environment:
    #  CONFIG_PATH: config/local.yaml
    #command: ["./main", "--config=./config/local.yaml"]

volumes:
  postgres_data: