env: local # dev, prod

storage:
  host: localhost
  port: 5432
  database: medods
  user: medods_admin
  password: medods_password

http_server:
  address: localhost:8082
  timeout: 4s
  idle_timeout: 60s

secret_key: medods
